version: "3"

services:
  goapp:
    build: .
    volumes:
      - .:/app
    ports:
      - 8080:8080
  mysql:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wallet
    ports:
      - 3306:3306
    volumes:
      - .docker/mysql:/var/lib/mysql
