// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package database

import (
	"github.com.br/Leodf/walletcore/balances/domain/repository"
)

type Balance = repository.RepositoryOutput
