// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: queries.sql

package database

import (
	"context"
	"time"
)

const checkAccountIdExists = `-- name: CheckAccountIdExists :one
SELECT EXISTS( SELECT id, account_id, amount, last_update FROM balances WHERE account_id = ?)
`

func (q *Queries) CheckAccountIdExists(ctx context.Context, accountID string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkAccountIdExists, accountID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const findBalancesByAccountId = `-- name: FindBalancesByAccountId :many
SELECT id, account_id, amount, last_update FROM balances WHERE account_id = ?
`

func (q *Queries) FindBalancesByAccountId(ctx context.Context, accountID string) ([]Balance, error) {
	rows, err := q.db.QueryContext(ctx, findBalancesByAccountId, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Balance
	for rows.Next() {
		var i Balance
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Amount,
			&i.LastUpdate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveBalances = `-- name: SaveBalances :exec
INSERT INTO balances (id, account_id, amount, last_update) VALUES
(?, ?, ?, ?),
(?, ?, ?, ?)
`

type SaveBalancesParams struct {
	ID           string
	AccountID    string
	Amount       int32
	LastUpdate   time.Time
	ID_2         string
	AccountID_2  string
	Amount_2     int32
	LastUpdate_2 time.Time
}

func (q *Queries) SaveBalances(ctx context.Context, arg SaveBalancesParams) error {
	_, err := q.db.ExecContext(ctx, saveBalances,
		arg.ID,
		arg.AccountID,
		arg.Amount,
		arg.LastUpdate,
		arg.ID_2,
		arg.AccountID_2,
		arg.Amount_2,
		arg.LastUpdate_2,
	)
	return err
}
