POST http://localhost:3000/clients
Content-Type: application/json

{
  "name": "Gaus",
  "email": "gaus@email.com"
}
###
POST http://localhost:3000/accounts
Content-Type: application/json

{
  "clientId": "0b1a0652-3f4f-4fec-a849-4b2d575e51d5"
}

###

POST http://localhost:8080/transactions
Content-Type: application/json

{
  "accountIdFrom": "f00aabf3-8ae7-4be1-b772-3138e136e44e",
  "accountIdTo": "ebdaf9ed-9498-4ac1-9a40-ce2bff41a7e6",
  "amount": 5000000000
}
